language: python

python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- nightly

install: "pip install -r requirements.txt"

cache:
- "$HOME/.monstercatconnect"

script:
- bash setup_travis.sh
- python notifier.py test

env:
  global:
  - secure: FKWjpQ63lLQSoQ6lM41YcYd+gpP9E2OdPDwhLron1SC8I10XIBXoD98Qw7d0mBglk3ZDOHag2v8XCutNPHdZGcfPgE2Q9uRCNjMGnquiLWsb8owsw46C2GH2L6nSCNqUrS+OnYRiLpGbAgIxeBEBArt9Ic6ONpHDl6KdsAMk5OUWNiLRkFFL8hQa+HdRKc26HMP8xUXrRRMd4eZk8SyAPW0GIrnN9eg2rMeangfOsD5D3USuuXwSCHOHUEpHUk96dQs4Qun2hv8ipjjlCZz1z/kD7uQn0/vnXZ+Yeasvofe/yEciw6U7dqHfMzJXHMs1KNBT/oDPHiW5ZV9/EbSUjDQHs064WTceJ5/aTY1Csvq4SS5x/TMrEUSo+3Vy7z/st2sQaaoOfvNIT34p3KVQwdaP3cxHMvv5t6Fes3vF/mXem0geGk6a/ha4SatdTkGci60uojHWOwt9/I1FpsZUj3lxTLHKioBmenTu1USt4P7aVVzpU/CXbfAc8YCTnKHihgUlniTPD2FwiiA4NtdimhjLdYH3I6Rq2n0yw7BDz/KtErQdTU077aiBoisLnVD8YkJ//3Q/ZqgPXAgYvMABHD7XjNWWlNsudF8arbm0Vq6s1fXhc2uC4k66TyQdVvwP1BQxQRTMe+ikh2AXwhjlqOwYz3mQQ213knJ6CqltFAs=
  - secure: 3xCpE4W8s1ZSHicnu6eTNuLvWPrciloyj7mAc0QWDVqjjVJYqnB9/SV0omXR/0jEZAAxt1d97RpPU7tMGMpnYZowwDMU6nX51X4vMLvcF6hZYZqqfSGbGACm4hYybEdnrlQ6kD8tpO9h4ubxFzfnq3jZvUUNyx5S2qwdGlVR1DkkGpbI8/HE6iZw0wxrkIQcvrxcJEOHJnRkhPGtKzJnqGdq7zD3wj5swTOyP53FN6s6RrB1QCCCUbjrsyM76pMI70H9eg13DTJx7B3AFZSjwSG8a5xaVWZHZobMA3/I51fwkeouo+0vCm2LciLB6SDi/eKVetjAPXxUdoOUn5Vzi9Bifa/Wm915gE8AcU2U9iynkPf9QJkEfeUZJRCjPaFYHhkhgLpGC5Vl0gkwSvrIZVpncUfPoDvKNTrEUQHNk6sc0iaJ2ywuhtqYaOl2I35360KhTV0Sd1Cz5SmsbT+cGUXTQ+zlbF7pBPKym9guHagoJtUZgLNHru7ySOehYXassVArMnTBe9HicNNfrpygKWqZA5dYCTtlL6MgF/IV9WtKvn6zGdZqFGKJUS654FnHKNMgaJcEjUm9fk+5FIdxJzDlZFr27kI2SKy6IIom0nM1YeacIOz5YpcAKYNx41JZtQLKZoyJGTPdmhQKgWq9pbMaiqW40UxjXI4xYoLPDr8=
  - secure: QxJrV6g2veTPJxBaHY6NRZbJAkqKBYHWG/7A5snPq3Khj3jUs/FmDEgGfkfvVd317xcCzie8l0YCttpMFbalDhMf77aMrJt95h0yhP11BURrwzxYZmVYMjcbOgK5f+S/rITsbOm2TpsVkT6jHNOJWvJhIW/1B+b6qDYbraC8yyv0hyUo/mBtf1n1pvSM24T6+55dBY9Rs4Gt2ZJCDdTAWEoMay8e26Fx+QuHaxfZ8qoRZpHyE4vQw3HayDC+OdL1lLvHL2KGfzpLqm47zIb0UIGYxTbFvy+yof7pT5MaVEBrB6wM0WiGrDpSt5rfj97eAf5y/cIGxFs9nsiWVp2hBGGllQnkW6iKdglAl+aYEMbZCdPdmAIn3h3ubMiDdA79X8dEA0sWYeSfGYkafHkqCQESAy+lpOVo84P6eXcg4msTvTOf4kQecCfQObUZ8X50dkiwCA/Y111zkiTOW015fcgtEItZmnMo0MaO2xxCxkDxOFtnf0yyK8v4lcsB16EsmMix+G+z24hIUOopg4UaTCVap+brQk89rXcmSVN2pZMomwYOeb8onDRXJ9ywAEy8URCHZ9cDZ7h+U1S0OABpGpX8BRHk5kMc2dTEBFWf5i/3B7Wi5VLEUiEmetTDZysVtPZ7WmMiL0SX3LuDikF3tSX2pFBtGAxUB1w0+0CxMe0=
  - secure: m1dV2txToxBtcL4hfn6iOvfUQ5jLUs6TgvPmJpsOw9rI3Einc2gr2+qnRQoGjDM41o4U7cVgKzNKQtNalxBxfYzKsQs625aO4kEMSIaK/0uDQkioLPYeQhPoKAo0zys4LkIOnTbFPsvfYGG5E8DNmMlVGfYTqa1DvCVE3tKElffQ6J6wyIYzsjTz48Qntw4a7M3Wwo9GYG1qaqqVy6bfSl6XUwHlU2IS+98j57cOW1OgVQzDlW3AVGBwDDzvOx35RU5E4a69oaLaARhurzux1PqyoCh7ik+6HqucEdLH56KGaNPLMN5VdPdQPe59r7e8BByMBdUoGa7jw102uiyQto85qmvcMYCyEcZc8E5IVYbhNTu1IAaJuOcT8NXfXz2lrlElpm4DxwAik3+L3VQA6KBSdZPB2YUQs1Al11u4uBcyH8q2DJrdQYuErHCzR9V9MUwQCK/BH2ZlO79RTS43ckNShgLonVRb04TEGKaoJHmpPOkHIUyXc5h399wKSSwVYosNBuBV87HS3IupRo42cmRgG4MXBs7U7OjHHPOHjjC0K7hkserMHCXWILW/hUDCjXbXfmOWXmAju12CvD8oxHaFu5D+6AOe+Mgv2sB9Mrsub5i103prjwHUjLYk+0GIcr+f+7kqPOrMjvVGchgxFhuHQXGfWoH7d7zvgXSalec=
